version: "3"
services:
  python_container:
    build:
      context: .
    environment:
      - HOME=/usr
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: /bin/bash
